Vagrant.configure("2") do |config|
  config.vm.box = "dreamscapes/archlinux"
  config.vm.network "forwarded_port", guest: 22, host: 2221
  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello~ IaaS: Provisioned!" >> /home/vagrant/hello.txt
    sudo pacman -Sy --noconfirm nano
  SHELL
end
